# Generated by Django 5.2.11 on 2026-04-29 09:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_author_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(3)]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/featured/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=80, unique=True),
        ),
    ]
